---
- name: 'Install anyenv'
  homebrew:
    name: 'anyenv'
    state: 'present'

# - name: 'clone anyenv'
#   git:
#     repo: 'https://github.com/anyenv/anyenv.git'
#     dest: ~/.anyenv

- name: 'Setup anyenv'
  blockinfile:
    dest: '~/.bash_profile'
    block: |
      if [ -e "$HOME/.anyenv" ]
      then
        export ANYENV_ROOT="$HOME/.anyenv"
        export PATH="$ANYENV_ROOT/bin:$PATH"
        if command -v anyenv 1>/dev/null 2>&1
        then
          eval "$(anyenv init -)"
        fi
      fi

- name: 'enable bash_profile'
  shell: 'source ~/.bash_profile'

- name: 'anyenv init'
  shell: 'anyenv install --force-init'