---
- name: 'Install pyenv'
  homebrew:
    name: 'pyenv'
    state: 'present'

# - name: 'Install pyenv with anyenv'
#   shell: 'anyenv install pyenv'

- name: 'Install pyenv-virtualenv'
  homebrew:
    name: 'pyenv-virtualenv'
    state: 'present'

- name: 'Add PATH'
  lineinfile:
    dest: '~/.bash_profile'
    line: '{{ item }}'
  with_items:
    - 'export PYENV_ROOT="${HOME}/.pyenv"'
    - 'export PATH=${PYENV_ROOT}/bin:${PYENV_ROOT}/shims:${PATH}'

- name: 'Setup pyenv-virtualenv'
  blockinfile:
    dest: '~/.bash_profile'
    block: |
      if [ -d "${PYENV_ROOT}" ]; then
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
      fi

- name: 'enable bash_profile'
  shell: 'source ~/.bash_profile'

- name: 'Install Python 3.6.1'
  shell: 'pyenv install 3.6.1'
  ignore_errors: yes

- name: 'Install Python 3.6.1'
  shell: 'pyenv virtualenv 3.6.1 py361'
  ignore_errors: yes




