---
mas_apps:
  - id: 1295203466
    name: 'Microsoft Remote Desktop'
  - id: 425955336
    name: 'Skitch'
  - id: 414855915
    name: 'WinArchiver Lite'
  - id: 490461369
    name: 'Bandwidth+'
  - id: 883070818
    name: 'SafeInCloud'
