---
- include: 'mac_default_write.yml'
- include: 'preconditions.yml'
- include: 'tools.yml'
- include: 'git.yml'
- include: 'nodejs.yml'
- include: 'docker.yml'
- include: 'google-japanese-ime.yml'
- include: 'intellj.yml'
- include: 'slack.yml'
- include: 'iterm2.yml'
- include: 'chrome.yml'
- include: 'editor.yml'
- include: 'gh.yml'
- include: 'dbeaver.yml'
- include: 'clipy.yml'