name: Ansible Lint

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@v4.1.0
      with:
        targets: ansible/mac/playbooks/my-mac.yml
        args: ""
